name: Run Selenium Pytest Tests

on:
  workflow_dispatch:     #  enables manual trigger via GitHub UI
#  schedule:
#    - cron: '0 0 * * *'  #  scheduled daily at midnight (UTC)

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run Pytest and generate HTML Report  #added HTML Report
      run: |
        mkdir -p reports
        pytest --html=reports/report.html --self-contained-html --maxfail=1 --disable-warnings -v

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: reports/report.html
